packages:
  - '.'
  - 'serverless'
  - 'serverless/*'
  - 'serverless/*/dashboard'
  - 'serverless/*/app'
  - 'serverless/shared/api'
  - 'control-panel'
  - 'mods-hub'
  - 'shared-components'
  - 'shared-components/*'

