packages:
  - '.'
  - 'serverless'
  - 'serverless/*'
  - 'serverless/*/dashboard'
  - 'serverless/*/app'
  - 'packages/api-framework'
  - 'packages/service-client'
  - 'packages/types'
  - 'packages/e2e-helpers'
  - 'packages/otp-login'
  - 'packages/search-query-parser'
  - 'packages/virtualized-table'
  - 'packages/rate-limit-info'
  - 'packages/status-flair'
  - 'packages/tooltip'
  - 'packages/ad-carousel'
  - 'packages/error-mapping'
  - 'packages/idle-game-overlay'
  - 'packages/auth-store'
  - 'packages/customer-lookup'
  - 'packages/asciimoji'
  - 'dice-board-game'
  - 'control-panel'
  - 'mods-hub'
  - 'shared-components'

