#!/usr/bin/env node
/**
 * Setup mods-hub .env file
 * 
 * This script ensures .env exists for Vite environment variables.
 * All encryption uses JWT tokens from authentication - no service keys needed.
 */

import { existsSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const MODS_HUB_DIR = __dirname;
const ENV_FILE = join(MODS_HUB_DIR, '.env');

/**
 * Setup .env file for mods-hub
 * Just ensures .env exists - no encryption keys needed (JWT only)
 */
function setupEnv() {
  if (!existsSync(ENV_FILE)) {
    // Create minimal .env file
    const envContent = `# Mods Hub - Development Environment Variables
# Auto-generated by setup-env.js
# This file is gitignored and used by Vite
# 
# All encryption uses JWT tokens from authentication.
# No service encryption keys are needed.
`;
    writeFileSync(ENV_FILE, envContent, 'utf-8');
    console.log('✓ Created .env file');
  }
  
  console.log('✓ Setup complete');
}

// Run setup
setupEnv();

