#!/usr/bin/env node
/**
 * Setup mods-hub .env file from worker .dev.vars
 * 
 * This script ensures VITE_SERVICE_ENCRYPTION_KEY is set in mods-hub/.env
 * by reading it from serverless/otp-auth-service/.dev.vars
 * 
 * CRITICAL: Both must use the same key value for encryption to work
 */

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const MODS_HUB_DIR = __dirname;
const ROOT_DIR = join(MODS_HUB_DIR, '..');
const OTP_AUTH_DIR = join(ROOT_DIR, 'serverless', 'otp-auth-service');

const ENV_FILE = join(MODS_HUB_DIR, '.env');
const DEV_VARS_FILE = join(OTP_AUTH_DIR, '.dev.vars');

/**
 * Extract SERVICE_ENCRYPTION_KEY from .dev.vars
 */
function getServiceKeyFromDevVars() {
  if (!existsSync(DEV_VARS_FILE)) {
    console.error('✗ .dev.vars not found at:', DEV_VARS_FILE);
    console.error('ℹ Run: cd serverless/otp-auth-service && pnpm setup:test-secrets');
    return null;
  }
  
  const content = readFileSync(DEV_VARS_FILE, 'utf-8');
  
  // Try SERVICE_ENCRYPTION_KEY first (worker uses this)
  let match = content.match(/^SERVICE_ENCRYPTION_KEY=(.+)$/m);
  if (match) {
    return match[1].trim();
  }
  
  // Fallback to VITE_SERVICE_ENCRYPTION_KEY (some workers set both)
  match = content.match(/^VITE_SERVICE_ENCRYPTION_KEY=(.+)$/m);
  if (match) {
    return match[1].trim();
  }
  
  console.error('✗ SERVICE_ENCRYPTION_KEY not found in .dev.vars');
  return null;
}

/**
 * Setup .env file for mods-hub
 */
function setupEnv() {
  const serviceKey = getServiceKeyFromDevVars();
  if (!serviceKey) {
    console.error('✗ Could not get SERVICE_ENCRYPTION_KEY from .dev.vars');
    process.exit(1);
  }
  
  let envContent = '';
  
  // If .env exists, read it and update VITE_SERVICE_ENCRYPTION_KEY
  if (existsSync(ENV_FILE)) {
    envContent = readFileSync(ENV_FILE, 'utf-8');
    
    // Check if VITE_SERVICE_ENCRYPTION_KEY already exists
    if (envContent.match(/^VITE_SERVICE_ENCRYPTION_KEY=/m)) {
      // Update existing key
      envContent = envContent.replace(
        /^VITE_SERVICE_ENCRYPTION_KEY=.*$/m,
        `VITE_SERVICE_ENCRYPTION_KEY=${serviceKey}`
      );
      console.log('✓ Updated VITE_SERVICE_ENCRYPTION_KEY in .env');
    } else {
      // Add key if missing
      envContent += `\nVITE_SERVICE_ENCRYPTION_KEY=${serviceKey}\n`;
      console.log('✓ Added VITE_SERVICE_ENCRYPTION_KEY to .env');
    }
  } else {
    // Create new .env file
    envContent = `# Mods Hub - Development Environment Variables
# Auto-generated by setup-env.js
# This file is gitignored and used by Vite

VITE_SERVICE_ENCRYPTION_KEY=${serviceKey}
`;
    console.log('✓ Created .env file with VITE_SERVICE_ENCRYPTION_KEY');
  }
  
  writeFileSync(ENV_FILE, envContent, 'utf-8');
  console.log('ℹ VITE_SERVICE_ENCRYPTION_KEY synced from worker .dev.vars');
  console.log('ℹ Key length:', serviceKey.length);
}

// Run setup
setupEnv();

