#!/usr/bin/env node
/**
 * Setup mods-hub .env file
 * 
 * NOTE: Service key encryption has been removed.
 * This script is kept for backward compatibility but no longer sets VITE_SERVICE_ENCRYPTION_KEY.
 * All encryption now uses JWT tokens.
 */

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const MODS_HUB_DIR = __dirname;
const ENV_FILE = join(MODS_HUB_DIR, '.env');

/**
 * Setup .env file for mods-hub
 * Service key encryption removed - this script now just ensures .env exists
 */
function setupEnv() {
  console.log('ℹ Service key encryption has been removed. All encryption now uses JWT tokens.');
  
  // If .env exists, remove any VITE_SERVICE_ENCRYPTION_KEY references
  if (existsSync(ENV_FILE)) {
    let envContent = readFileSync(ENV_FILE, 'utf-8');
    
    // Remove VITE_SERVICE_ENCRYPTION_KEY if present
    if (envContent.match(/^VITE_SERVICE_ENCRYPTION_KEY=/m)) {
      envContent = envContent.replace(/^VITE_SERVICE_ENCRYPTION_KEY=.*$/m, '');
      envContent = envContent.replace(/\n\n+/g, '\n'); // Clean up extra newlines
      writeFileSync(ENV_FILE, envContent.trim() + '\n', 'utf-8');
      console.log('✓ Removed VITE_SERVICE_ENCRYPTION_KEY from .env (no longer needed)');
    } else {
      console.log('ℹ .env file exists and does not contain VITE_SERVICE_ENCRYPTION_KEY');
    }
  } else {
    // Create minimal .env file
    const envContent = `# Mods Hub - Development Environment Variables
# Auto-generated by setup-env.js
# This file is gitignored and used by Vite
# 
# NOTE: Service key encryption has been removed.
# All encryption now uses JWT tokens from authentication.
`;
    writeFileSync(ENV_FILE, envContent, 'utf-8');
    console.log('✓ Created minimal .env file');
  }
  
  console.log('✓ Setup complete - no service key needed');
}

// Run setup
setupEnv();

