#!/usr/bin/env node
/**
 * Setup mods-hub .env file
 * 
 * This script ensures .env exists for Vite environment variables.
 * Mod files are encrypted with shared key encryption (MODS_ENCRYPTION_KEY).
 */

import { existsSync, writeFileSync, readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const MODS_HUB_DIR = __dirname;
const ENV_FILE = join(MODS_HUB_DIR, '.env');

/**
 * Setup .env file for mods-hub
 * Creates .env with shared encryption key for mod file encryption
 */
function setupEnv() {
  const sharedKey = 'strixun_mods_encryption_key_dev_2025_secure_random_64_char_minimum_required_for_pbkdf2_derivation';
  
  // Read existing .env if it exists
  let existingContent = '';
  if (existsSync(ENV_FILE)) {
    existingContent = readFileSync(ENV_FILE, 'utf-8');
  }
  
  // Check if VITE_MODS_ENCRYPTION_KEY already exists
  if (existingContent.includes('VITE_MODS_ENCRYPTION_KEY')) {
    console.log('✓ .env file already has VITE_MODS_ENCRYPTION_KEY');
    return;
  }
  
  // Append or create with encryption key
  const envContent = existingContent 
    ? `${existingContent}\n# Shared encryption key for mod file encryption\n# Must match MODS_ENCRYPTION_KEY in serverless/mods-api\nVITE_MODS_ENCRYPTION_KEY=${sharedKey}\n`
    : `# Mods Hub - Development Environment Variables
# Auto-generated by setup-env.js
# This file is gitignored and used by Vite
#
# Shared encryption key for mod file encryption
# Must match MODS_ENCRYPTION_KEY in serverless/mods-api
VITE_MODS_ENCRYPTION_KEY=${sharedKey}
`;
  
  writeFileSync(ENV_FILE, envContent, 'utf-8');
  console.log('✓ Created/updated .env file with VITE_MODS_ENCRYPTION_KEY');
}

// Run setup
setupEnv();

