/**
 * App Assets Handler
 * 
 * Serves the built Svelte app
 * Handles SPA routing - all non-API paths serve the app
 */

// Import the bundled app assets (embedded at build time)
// This is generated by scripts/build-app.js
import { APP_ASSETS } from '../dist/app-assets.js';

interface Env {
  ENVIRONMENT?: string;
  [key: string]: unknown;
}

/**
 * Get content type from file path
 */
function getContentType(path: string): string {
  const ext = path.split('.').pop()?.toLowerCase();
  const contentTypes: Record<string, string> = {
    html: 'text/html; charset=utf-8',
    js: 'application/javascript; charset=utf-8',
    css: 'text/css; charset=utf-8',
    json: 'application/json; charset=utf-8',
    png: 'image/png',
    jpg: 'image/jpeg',
    jpeg: 'image/jpeg',
    svg: 'image/svg+xml',
    ico: 'image/x-icon',
    woff: 'font/woff',
    woff2: 'font/woff2',
  };
  return contentTypes[ext || ''] || 'text/plain; charset=utf-8';
}

/**
 * Serve app assets
 * GET /* (non-API paths)
 */
export async function handleAppAssets(request: Request, env: Env): Promise<Response> {
  const url = new URL(request.url);
  let path = url.pathname;

  // Remove leading slash for asset lookup
  if (path.startsWith('/')) {
    path = path.slice(1);
  }

  // For root or non-existent paths, serve index.html (SPA routing)
  if (!path || path === '/' || !APP_ASSETS[path]) {
    path = 'index.html';
  }

  // Get asset content
  const content = APP_ASSETS[path];
  if (!content) {
    // Fallback to index.html for SPA routing
    const indexContent = APP_ASSETS['index.html'];
    if (indexContent) {
      return new Response(indexContent, {
        headers: {
          'Content-Type': 'text/html; charset=utf-8',
          'Cache-Control': 'no-cache',
        },
      });
    }
    return new Response('Not Found', { status: 404 });
  }

  // Check if it's a data URI (binary file)
  const contentType = content.startsWith('data:') 
    ? content.split(';')[0].split(':')[1]
    : getContentType(path);

  // If it's a data URI, we need to extract the base64 content
  if (content.startsWith('data:')) {
    const base64 = content.split(',')[1];
    const buffer = Uint8Array.from(atob(base64), c => c.charCodeAt(0));
    return new Response(buffer, {
      headers: {
        'Content-Type': contentType,
        'Cache-Control': 'public, max-age=31536000',
      },
    });
  }

  return new Response(content, {
    headers: {
      'Content-Type': contentType,
      'Cache-Control': path === 'index.html' ? 'no-cache' : 'public, max-age=31536000',
    },
  });
}

