/**
 * Decryption Script Handler
 * 
 * Serves the bundled decryptWithJWT script for use in standalone HTML
 * The script is built from the actual shared library code
 * CRITICAL: JWT binary encryption is MANDATORY for all binary responses
 */

// Import the bundled script (embedded at build time)
// This is generated by scripts/bundle-decrypt.js
import { BUNDLED_DECRYPT_SCRIPT } from '../dist/decrypt-script.js';
import { encryptBinaryWithJWT } from '@strixun/api-framework';
import { getCorsHeaders } from '../utils/cors.js';

/**
 * Serve bundled decryption script
 * GET /decrypt.js
 */
export async function handleDecryptScript(request, env) {
  // CRITICAL SECURITY: JWT binary encryption is MANDATORY for all binary responses
  // Get JWT token from request
  const authHeader = request.headers.get('Authorization');
  const jwtToken = authHeader?.startsWith('Bearer ') ? authHeader.substring(7) : null;
  
  if (!jwtToken) {
    const errorResponse = {
      type: 'https://tools.ietf.org/html/rfc7235#section-3.1',
      title: 'Unauthorized',
      status: 401,
      detail: 'JWT token is required for encryption/decryption. Please provide a valid JWT token in the Authorization header.',
      instance: request.url
    };
    const corsHeaders = getCorsHeaders(env, request);
    return new Response(JSON.stringify(errorResponse), {
      status: 401,
      headers: {
        'Content-Type': 'application/problem+json',
        ...corsHeaders,
      },
    });
  }

  // Convert JavaScript code to binary and encrypt with JWT
  const encoder = new TextEncoder();
  const codeBytes = encoder.encode(BUNDLED_DECRYPT_SCRIPT);
  const encryptedCode = await encryptBinaryWithJWT(codeBytes, jwtToken);

  const corsHeaders = getCorsHeaders(env, request);
  return new Response(encryptedCode, {
    headers: {
      ...corsHeaders,
      'Content-Type': 'application/octet-stream', // Binary encrypted data
      'X-Encrypted': 'true', // Flag to indicate encrypted response
      'X-Original-Content-Type': 'application/javascript; charset=utf-8', // Preserve original content type
      'Cache-Control': 'public, max-age=3600',
    },
  });
}

