/**
 * Decryption Script Handler
 * 
 * Serves the bundled decryptWithJWT script for use in standalone HTML
 * The script is built from the actual shared library code
 * CRITICAL: JWT binary encryption is MANDATORY for all binary responses
 */

// Import the bundled script (embedded at build time)
// This is generated by scripts/bundle-decrypt.js
import { BUNDLED_DECRYPT_SCRIPT } from '../dist/decrypt-script.js';
import { encryptBinaryWithJWT } from '@strixun/api-framework';
import { getCorsHeaders } from '../utils/cors.js';

/**
 * Serve bundled decryption script
 * GET /decrypt.js
 */
export async function handleDecryptScript(request, env) {
  // Get JWT token from request (optional - serve unencrypted if no token)
  const authHeader = request.headers.get('Authorization');
  const jwtToken = authHeader?.startsWith('Bearer ') ? authHeader.substring(7) : null;
  
  const corsHeaders = getCorsHeaders(env, request);
  
  // If JWT token is provided, encrypt the script
  if (jwtToken) {
    try {
      // Convert JavaScript code to binary and encrypt with JWT
      const encoder = new TextEncoder();
      const codeBytes = encoder.encode(BUNDLED_DECRYPT_SCRIPT);
      const encryptedCode = await encryptBinaryWithJWT(codeBytes, jwtToken);

      return new Response(encryptedCode, {
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/octet-stream', // Binary encrypted data
          'X-Encrypted': 'true', // Flag to indicate encrypted response
          'X-Original-Content-Type': 'application/javascript; charset=utf-8', // Preserve original content type
          'Cache-Control': 'public, max-age=3600',
        },
      });
    } catch (error) {
      // If encryption fails, fall back to unencrypted
      console.warn('[Decrypt Script] Encryption failed, serving unencrypted:', error);
    }
  }
  
  // Serve unencrypted script (public access - needed for initial authentication)
  // This is safe because the script itself doesn't contain secrets
  return new Response(BUNDLED_DECRYPT_SCRIPT, {
    headers: {
      ...corsHeaders,
      'Content-Type': 'application/javascript; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    },
  });
}

