/**
 * Decryption Script Handler
 * 
 * Serves the bundled decryptWithJWT script for use in standalone HTML
 * The script is built from the actual shared library code
 */

// Import the bundled script (embedded at build time)
// This is generated by scripts/bundle-decrypt.js
import { BUNDLED_DECRYPT_SCRIPT } from '../dist/decrypt-script.js';

/**
 * Serve bundled decryption script
 * GET /decrypt.js
 */
export async function handleDecryptScript() {
  return new Response(BUNDLED_DECRYPT_SCRIPT, {
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    },
  });
}

