/**
 * Build URL Shortener App Assets
 * 
 * Bundles the Svelte app and creates an assets file for the worker
 */

import { build } from 'vite';
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const projectRoot = join(__dirname, '..');
const appDir = join(projectRoot, 'app');
const distDir = join(appDir, 'dist');
const outputFile = join(projectRoot, 'app-assets.js');

try {
  // Build the Svelte app (already done by pnpm build:app script)
  // This script just processes the built files
  console.log('Processing built app files...');

  // Read all files from dist directory
  const { readdirSync, statSync } = await import('fs');
  const assets = {};
  
  function readDirectory(dir, basePath = '') {
    const entries = readdirSync(dir);
    
    for (const entry of entries) {
      const fullPath = join(dir, entry);
      const relativePath = basePath ? `${basePath}/${entry}` : entry;
      const stat = statSync(fullPath);
      
      if (stat.isDirectory()) {
        readDirectory(fullPath, relativePath);
      } else {
        const content = readFileSync(fullPath);
        const ext = entry.split('.').pop();
        
        // For binary files, convert to data URI
        if (['png', 'jpg', 'jpeg', 'svg', 'woff', 'woff2', 'ico'].includes(ext)) {
          const base64 = content.toString('base64');
          const mimeTypes = {
            png: 'image/png',
            jpg: 'image/jpeg',
            jpeg: 'image/jpeg',
            svg: 'image/svg+xml',
            woff: 'font/woff',
            woff2: 'font/woff2',
            ico: 'image/x-icon',
          };
          assets[relativePath] = `data:${mimeTypes[ext]};base64,${base64}`;
        } else {
          // Text files
          assets[relativePath] = content.toString('utf-8');
        }
      }
    }
  }
  
  readDirectory(distDir);
  
  // Generate assets file as TypeScript
  const assetsContent = `// URL Shortener App Assets
// This file is auto-generated by scripts/build-app.js
// Do not edit manually

const assets: Record<string, string> = ${JSON.stringify(assets, null, 2)};

export default assets;
`;
  
  const outputFileTS = outputFile.replace('.js', '.ts');
  writeFileSync(outputFileTS, assetsContent);
  console.log(`[SUCCESS] Built app assets to ${outputFileTS}`);
  console.log(`   Found ${Object.keys(assets).length} files`);
} catch (error) {
  console.error('[ERROR] Failed to build app:', error);
  process.exit(1);
}

