/**
 * Entry point for bundling decryptWithJWT
 * This file is generated by bundle-decrypt.js
 */

import { decryptWithJWT } from '../../shared/encryption/jwt-encryption.js';

// Export to window for browser use
if (typeof window !== 'undefined') {
  (window as any).decryptWithJWT = decryptWithJWT;
} else {
  // For Node.js/Workers testing
  (globalThis as any).decryptWithJWT = decryptWithJWT;
}

